export const GET_HOSTS = 'GET_HOSTS'
export const SELECT_HOST = 'SELECT_HOST'
export const SET_USER = 'SET_USER'
export const NEW_FRAME = 'NEW_FRAME'
export const MOUSE_LCLICK = 'MOUSE_LCLICK'
export const SET_SETTINGS = 'SET_SETTINGS'
